import { describe, expect, it } from "vitest";
import {
  EC_STRATEGIES,
  parseBotConfig,
  supportFor,
  toPrismEnv,
  type BotConfig,
} from "@sdk/bot/config";

/**
 * The parser is the whole integration contract.
 *
 * A dreamBot Builder config is a block of text a user pastes, and everything
 * downstream — how much it trades, whether it signs at all, which strategy runs
 * — comes out of this one function. A silent misparse does not throw; it
 * trades, with the wrong size, or with signing armed when the user thought it
 * was not. So the failure directions matter more than the happy path.
 */

/** Exactly what the Builder emitted for EC Starter, verified by walking it. */
const BUILDER_OUTPUT = `# DreamDEX bot config — generated by the Bot Builder
# 1) Add your own funded key below. Never share it, never commit this file.
# 2) Save this as \`.env\` in the dreamdex-bot-kit folder.

NETWORK=testnet
DRY_RUN=true
STRATEGY=ec-starter
PRIVATE_KEY=0x...

TAKE_MAX_SHARES=5
TAKE_MAX_POSITION=20
TAKE_INTERVAL_MS=8000
`;

const ok = (text: string): BotConfig => {
  const r = parseBotConfig(text);
  if (!r.ok) throw new Error(`expected a parse, got: ${r.error}`);
  return r.config;
};

describe("the Builder's actual output", () => {
  it("parses the block verbatim, comments, blank lines and all", () => {
    const c = ok(BUILDER_OUTPUT);
    expect(c.strategy).toBe("ec-starter");
    expect(c.network).toBe("testnet");
    expect(c.dryRun).toBe(true);
    expect(c.maxShares).toBe(5);
    expect(c.maxPosition).toBe(20);
    expect(c.intervalMs).toBe(8000);
  });

  it("treats the untouched 0x... placeholder as no key", () => {
    // The Builder ships a literal `PRIVATE_KEY=0x...` for the user to replace.
    // Reading that as a key would arm a runner with a wallet that cannot sign.
    expect(ok(BUILDER_OUTPUT).hasKey).toBe(false);
  });

  it("flags nothing unknown in a stock config", () => {
    expect(ok(BUILDER_OUTPUT).unknownKeys).toEqual([]);
  });
});

describe("the key never leaves the file it came in", () => {
  const withKey = BUILDER_OUTPUT.replace("PRIVATE_KEY=0x...", `PRIVATE_KEY=0x${"a".repeat(64)}`);

  it("reports that a key is present without carrying its value", () => {
    const c = ok(withKey);
    expect(c.hasKey).toBe(true);
    // The whole config object gets logged and serialised into errors. If the
    // key rode along, it would end up in a log line eventually.
    expect(JSON.stringify(c)).not.toContain("a".repeat(64));
  });

  it("keeps the key out of the derived environment too", () => {
    expect(JSON.stringify(toPrismEnv(ok(withKey)))).not.toContain("a".repeat(64));
  });

  it("warns when the key is missing its 0x prefix rather than accepting it", () => {
    const c = ok(BUILDER_OUTPUT.replace("PRIVATE_KEY=0x...", `PRIVATE_KEY=${"a".repeat(64)}`));
    expect(c.hasKey).toBe(false);
    expect(c.warnings.join(" ")).toContain("0x");
  });
});

describe("signing is armed only by an explicit false", () => {
  it("keeps dry run on when DRY_RUN is absent", () => {
    expect(ok("STRATEGY=ec-starter").dryRun).toBe(true);
  });

  it("arms only on the exact string false", () => {
    expect(ok("STRATEGY=ec-starter\nDRY_RUN=false").dryRun).toBe(false);
  });

  it("refuses to arm on a value it does not understand", () => {
    // "no", "0" and "off" all read as "not dry run" to a careless parser, and
    // every one of them would start signing.
    for (const v of ["no", "0", "off", "FALSE ", "yes"]) {
      const c = ok(`STRATEGY=ec-starter\nDRY_RUN=${v}`);
      if (v.trim().toLowerCase() === "false") continue;
      expect(c.dryRun, `DRY_RUN=${v} must not arm signing`).toBe(true);
    }
  });
});

describe("a config that cannot be understood is refused, never defaulted", () => {
  it("rejects an empty config", () => {
    expect(parseBotConfig("").ok).toBe(false);
    expect(parseBotConfig("   \n\n").ok).toBe(false);
  });

  it("rejects prose that contains no assignments", () => {
    expect(parseBotConfig("paste your config here").ok).toBe(false);
  });

  it("rejects a config with no STRATEGY rather than picking one", () => {
    const r = parseBotConfig("NETWORK=testnet\nDRY_RUN=true");
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error).toContain("STRATEGY");
  });

  it("rejects the Builder's Spot strategies, which are a different venue surface", () => {
    const r = parseBotConfig("STRATEGY=market-maker");
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error).toContain("Event Contracts");
  });

  it("rejects an unrecognised network", () => {
    expect(parseBotConfig("STRATEGY=ec-starter\nNETWORK=devnet").ok).toBe(false);
  });
});

describe("tuned parameters", () => {
  it("finds them under any strategy prefix, not just TAKE_", () => {
    // Only ec-starter was walked. A maker's prefix is presumably different, and
    // pinning TAKE_ would silently fall back to defaults — a wrong size that
    // trades, rather than a config that is rejected.
    const c = ok("STRATEGY=ec-starter\nMAKE_MAX_SHARES=3\nMAKE_INTERVAL_MS=2500");
    expect(c.maxShares).toBe(3);
    expect(c.intervalMs).toBe(2500);
  });

  it("falls back and warns on a value that is not a positive number", () => {
    const c = ok("STRATEGY=ec-starter\nTAKE_MAX_SHARES=abc");
    expect(c.maxShares).toBe(1);
    expect(c.warnings.join(" ")).toContain("MAX_SHARES");
  });

  it("refuses a zero or negative size instead of sending it", () => {
    expect(ok("STRATEGY=ec-starter\nTAKE_MAX_SHARES=0").maxShares).toBe(1);
    expect(ok("STRATEGY=ec-starter\nTAKE_MAX_SHARES=-4").maxShares).toBe(1);
  });

  it("reads a blank underlying as 'whatever the venue is running'", () => {
    expect(ok("STRATEGY=ec-starter").asset).toBeNull();
  });

  it("reads BTC and ETH, and warns on anything else", () => {
    expect(ok("STRATEGY=ec-starter\nTAKE_ASSET=btc").asset).toBe("BTC");
    const c = ok("STRATEGY=ec-starter\nTAKE_ASSET=DOGE");
    expect(c.asset).toBeNull();
    expect(c.warnings.join(" ")).toContain("DOGE");
  });

  it("tolerates quotes, export prefixes and trailing comments", () => {
    const c = ok(`export STRATEGY="ec-starter"\nTAKE_MAX_SHARES=7 # per trade`);
    expect(c.strategy).toBe("ec-starter");
    expect(c.maxShares).toBe(7);
  });

  it("surfaces keys it did not recognise instead of dropping them silently", () => {
    expect(ok("STRATEGY=ec-starter\nSOME_NEW_KNOB=3").unknownKeys).toContain("SOME_NEW_KNOB");
  });
});

describe("support is stated per strategy, never assumed", () => {
  it("covers every strategy the Builder offers", () => {
    for (const s of EC_STRATEGIES) {
      const verdict = supportFor({ strategy: s } as BotConfig);
      expect(verdict, `${s} has no support verdict`).toBeDefined();
      expect(verdict.reason.length).toBeGreaterThan(0);
    }
  });

  it("runs every strategy the Builder offers", () => {
    // The three resting ones were refused until sdk/dreamdex/cancel.ts existed:
    // placing a post-only order that could never be pulled leaves escrow locked
    // in a market that settles. With cancellation they are all runnable.
    for (const s of EC_STRATEGIES) {
      expect(supportFor({ strategy: s } as BotConfig).supported, `${s} is refused`).toBe(true);
    }
  });
});

describe("mapping onto PRISM's own environment", () => {
  it("carries network, dry run and size across", () => {
    const env = toPrismEnv(ok(BUILDER_OUTPUT));
    expect(env.PRISM_NETWORK).toBe("testnet");
    expect(env.PRISM_DRY_RUN).toBe("true");
    expect(env.PRISM_MAX_ORDER_CONTRACTS).toBe("5");
  });

  it("keeps PRISM's fail-safe: a dry-run config never maps to armed", () => {
    expect(toPrismEnv(ok("STRATEGY=ec-starter")).PRISM_DRY_RUN).toBe("true");
  });
});
